### ISSUE TITLE
Research about types of interactive and adaptive learning technologies.

### ISSUE THREAD

**Issue by Nintails-TF** [Nintails-TF/agile-smart-campus#1]
User Story: As a student, I want classrooms equipped with interactive and adaptive learning technologies to enhance my learning experience. 

DoD (Definition of Done): 4 examples of interactive and adaptive learning solutions.

**Comment by 2418560** [comment]
Interactive, requiring user input to do things?

Dynamic quizes that will provide in depth feedback to the instructor by clearly breaking down the results of each quiz, such as which were most commonly incorrect.  An example of quizes being used within education is Quizlet, Kahoot, or the system currently employed by the University of Dundee via Blackboard.

Allow educators to adaptively suggest resources to individual students either by specific key words assigned by educators and then searched by the students, OR suggesting resources based on results recieved from interactive quizes.

For in-person teaching, allow for a non-interruptive way for a student to highlight an issue or question without having the interrupt the flow of the lesson. Potentially suggest resources or pre-written answers to questions based on key words and tags.

Able to highlight which students are scoring consistently poorly on each question to potentially allow the educator to provide support. This could be done based on a variety of factors, including test results, monitoring how much content the student opens and views and attendance to sessions. Coursera uses a similar method to provide targetted support. https://spotlightr.com/5-adaptive-learning-examples-duplicating-their-success/
