### ISSUE TITLE
Research technological solutions for waste management, to promote campus environment footprint.

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#12]
As a facilities coordinator, I need advanced waste management systems focusing on recycling and composting, to minimize the campus's environmental footprint.

**Comment by FinnbarHome** [comment]
[Recyling n waste user story.docx](https://github.com/Nintails-TF/agile-smart-campus/files/13975659/Recyling.n.waste.user.story.docx)
