### ISSUE TITLE
Research examples of technological solutions to notify and inform people of schedule changes

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#15]
As a student, I want to receive real-time notifications about class schedule changes, room assignments, and campus events on my smartphone to stay informed and plan my day effectively.

**Comment by Lucca-C** [comment]
https://www.frontiersin.org/articles/10.3389/fpsyg.2022.767389/full
Digital Real-Time Learning System with Push Notifications: This system combines digital real-time learning, roll-call, and feedback collection functions. It improves online teaching quality by sending questions and roll-calls through push notifications, enabling teachers to monitor student concentration and participation​​.

https://link.springer.com/chapter/10.1007/978-981-19-4910-4_12
University Event Notification System with SMS Technology: A study focused on developing a web-based university notification system integrated with SMS technology. This system was particularly designed to facilitate user tasks, storing student and event details for efficient communication and information dissemination​​.

Mobile Notification System for Al Buraimi University: This case study involved developing a mobile notification system to provide real-time information to end-users. It aimed to enhance communication between students and educators, focusing on timely updates and information sharing​​.
