### ISSUE TITLE
Research examples of technology used to help navigate buildings or systems and highlight points of interest

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#17]
- [ ] #23

DoD (Definition of Done) - 3 examples of solutions that would be used to help navigate buildings / systems and highlight points of interest

**Comment by KyleTait01** [comment]
User Story: As a visitor, I want to easily navigate the campus using a mobile app that provides turn-by-turn directions, highlighting key facilities and points of interest

Could: This feature would be nice to have but is not necessary or vital for the success of the project

High Value: This feature would be useful for allowing visitors to find their way through the campus and would reduce the risk of time being wasted by being lost

Low Risk: This feature shouldn't generate any issues or problems

Indoor Navigation Apps - Technologies like indoor navigation apps use beacons, Wi-Fi signals, or Bluetooth to provide real-time guidance inside buildings. Apps such as IndoorAtlas or Google Maps can help users navigate complex structures, highlighting points of interest along the way.
https://techwiser.com/indoor-wayfinding-and-navigation/

Augmented Reality Wayfinding - AR technologies can overlay digital information onto the user's physical surroundings. Apps like ARWay or AR navigation features in Google Maps can highlight points of interest and guide users with visual cues.
https://www.arway.ai/post/navigating-the-future-activating-your-arway-map-for-enhanced-indoor-wayfinding 

Radio-frequency Identification (RFID) and Near Field Communication (NFC) - these technologies can be used in building navigation systems. These can be embedded in ID cards or mobile devices, allowing users to access secured areas, and these systems can also highlight points of interest within a facility.
https://www.techtarget.com/iotagenda/definition/RFID-radio-frequency-identification
