### ISSUE TITLE
Research about technological solutions for students with disabilities

### ISSUE THREAD

**Issue by Nintails-TF** [Nintails-TF/agile-smart-campus#2]
User Story: As a student with disabilities, I want all technological solutions to be accessible so that I can fully participate in campus life. 

DoD (Definition of Done): 4 examples of accessible technology solutions used for companies or university campuses.

**Comment by TheSloanRanger** [comment]
#7

**Comment by TheSloanRanger** [comment]
# Student Disabilities Research

## Types of student disabilities:

- Wheelchair users
- Deaf
- Blind
- Mute
- Lucca

## Technological Solutions

- Interactive Storybooks
- Text-to-speech
- Braille
- Accessible learning video games
- Slip-and-puff systems for mobility disabilities such as paralysis.
- Proofreading software for dyslexia and other learning difficulties
