### ISSUE TITLE
Research about VR and AR labs

### ISSUE THREAD

**Issue by Nintails-TF** [Nintails-TF/agile-smart-campus#4]
User Story: As a Staff Member (Lecturer), I need VR and AR labs to provide immersive educational experiences that engage students in cutting-edge subjects. 

DoD (Definition of Done): 3 examples of VR/AR solutions that are used within schools or other organisations.

**Comment by Lucca-C** [comment]
https://www.classvr.com/vr-headsets/
![image](https://github.com/Nintails-TF/agile-smart-campus/assets/35308900/3b702cd9-66a2-42f5-a4fb-f9f1e90e1ea8)
Standalone, reliable, and affordable VR headsets for educational purposes. 
The product can be used from ages 7+.

**Comment by Lucca-C** [comment]
https://www.mdpi.com/2227-7102/10/8/198

Case study problems with VR in education:
- Lack of resources
- Complex maintenance 
- Few AR educational applications
- Overloaded curricula
