### ISSUE TITLE
Research about assistive technologies that staff use to help students.

### ISSUE THREAD

**Issue by Nintails-TF** [Nintails-TF/agile-smart-campus#8]
User Story: As a staff member, I need assistive technologies integrated into campus systems to support my work and interaction with students. 

DoD (Definition of Done): 3 examples of assistive technology solutions used within schools or organisations.

**Comment by Lucca-C** [comment]
https://builtin.com/edtech/assistive-technology-in-the-classroom
Speechify: This text-to-speech software captures written text and translates it into audio. It's particularly useful for reading textbooks and PDF assignments, aiding students with ADHD and dyslexia. Speechify is compatible with various devices, including Chrome browsers, iPhones, Macs, and Androids​​.

https://builtin.com/edtech/assistive-technology-in-the-classroom
Kurzweil 3000: A comprehensive literacy support system, Kurzweil 3000 offers a range of assistive technologies including speech-to-text and text-to-speech functions in 18 languages. This technology benefits students with vision impairments and ADHD. It also includes a font designed for dyslexic readers, which helps reduce letter confusion​​.

https://www.understood.org/articles/examples-of-assistive-technology-adaptive-tools
FM Listening Systems: These systems are designed to reduce background noise in the classroom while amplifying the teacher's voice. They are particularly beneficial for students with auditory processing issues, focusing difficulties, hearing impairments, autism spectrum disorder, and language processing challenges. The teacher wears a microphone that transmits to speakers around the room or to a personal receiver worn by the student​​.
