### ISSUE TITLE
Research about streamlining navigation or management

### ISSUE THREAD

**Issue by Nintails-TF** [Nintails-TF/agile-smart-campus#9]
As a student, I want a campus app that offers streamlined navigation, event management, and facility bookings for a more organized campus experience. 

DoD (Definition of Done): 3 examples streamlined management/navigation solutions used within organisations or universities

**Comment by KyleTait01** [comment]
Enterprise Resource Planning (ERP) - Many organisations use ERP systems such as SAP, Oracle, or Workday to streamline various processes, providing a centralised platform for efficient navigation and management.

Learning Management Systems (LMS) - Universities often use LMS platforms like Canvas, Moodle, or Blackboard to streamline academic processes. These systems help manage course content, student enrolment, grading, and communication, providing a cohesive and organised environment for both students and faculty.

Project Management Tools - Organisations often rely on project management solutions such as Asana, Trello, or Jira to streamline task assignment, collaboration, and progress tracking. These tools enhance communication and coordination among team members, promoting efficient project navigation and management.
